name: Publish Stable
'on':
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20.18.0
      - run: |
          npm install
          npm install -g @vscode/vsce
          vsce package
      - uses: actions/upload-artifact@v4
        with:
          name: vscode-always-sidebar.zip
          path: "*.vsix"
  publish-vscode-market-place:
    runs-on: ubuntu-latest
    needs: [build]
    if: success() && startsWith( github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20.18.0
      - run: |
          npm install
          npm install -g @vscode/vsce
          vsce package
          vsce publish
        env:
          VSCE_PAT: ${{ secrets.MARKETPLACE_PAT }}
        continue-on-error: true
  publish-ovsx:
    runs-on: ubuntu-latest
    needs: [build]
    if: success() && startsWith( github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20.18.0
      - run: |
          npm install
          npm install -g @vscode/vsce ovsx
          vsce package
          ovsx publish
        env:
          OVSX_PAT: ${{ secrets.OVSX_ACCESS_TOKEN }}
        continue-on-error: true
